package br.com.renatanutricionista.paciente.dto;

import br.com.renatanutricionista.ficha.identificacao.frequencia.alimentar.questionario.dto.InformacoesPreviasQuestionariosDTO;
import br.com.renatanutricionista.ficha.identificacao.historico.alimentar.dto.InformacoesPreviasHistoricosAlimentaresDTO;
import br.com.renatanutricionista.ficha.identificacao.historico.atividade.fisica.dto.InformacoesHistoricosAtividadeFisicaDTO;
import br.com.renatanutricionista.ficha.identificacao.historico.patologia.por.data.familiares.dto.InformacoesPreviasHistoricosFamiliaresPorDataDTO;
import br.com.renatanutricionista.ficha.identificacao.historico.social.dto.InformacoesPreviasHistoricosSociaisDTO;
import br.com.renatanutricionista.paciente.model.Paciente;
import br.com.renatanutricionista.tabelas.parametro.atendimento.paciente.model.AtendimentoPacienteParametro;
import lombok.Getter;


@Getter
public class PacientePreviaHistoricosDTO {

	private PacienteDTO paciente;
	private InformacoesPreviasHistoricosSociaisDTO informacoesPreviasHistoricosSociais;
	private InformacoesPreviasHistoricosAlimentaresDTO informacoesPreviasHistoricosAlimentares;
	private InformacoesHistoricosAtividadeFisicaDTO informacoesHistoricosAtividadeFisica;
	private InformacoesPreviasHistoricosFamiliaresPorDataDTO informacoesPreviasHistoricosPatologiaFamiliaresPorData;
	private InformacoesPreviasQuestionariosDTO informacoesPreviasQuestionariosFrequenciaAlimentar;
	
	
	public PacientePreviaHistoricosDTO(Paciente paciente, AtendimentoPacienteParametro atendimentoPacienteParametro) {
		this.paciente = new PacienteDTO(paciente);
		informacoesPreviasHistoricosSociais = new InformacoesPreviasHistoricosSociaisDTO(paciente, atendimentoPacienteParametro);
		informacoesPreviasHistoricosAlimentares = new InformacoesPreviasHistoricosAlimentaresDTO(paciente, atendimentoPacienteParametro);
		informacoesHistoricosAtividadeFisica = new InformacoesHistoricosAtividadeFisicaDTO(paciente, atendimentoPacienteParametro);
		informacoesPreviasHistoricosPatologiaFamiliaresPorData = new InformacoesPreviasHistoricosFamiliaresPorDataDTO(paciente, atendimentoPacienteParametro);
		informacoesPreviasQuestionariosFrequenciaAlimentar = new InformacoesPreviasQuestionariosDTO(paciente, atendimentoPacienteParametro);
	}
}
